// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env.DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  // Only set datasource if we have a real URL, otherwise let schema.prisma handle it
  ...(databaseUrl && databaseUrl !== "postgresql://placeholder:placeholder@localhost:5432/placeholder"
    ? { datasource: { url: databaseUrl } }
    : {}),
});
